### ISSUE TITLE
Unable to Run on RPI 3 B+

### ISSUE THREAD

**Issue by vsaravind007** [balenalabs/rosetta-at-home#17]
Hello,

I've successfully completed the setup & my Pi is up & running, however I'm getting messages similar to the following on my web interface:

`Rosetta needs 1716.61 MB RAM but only 966.83 MB is available for use.`

![image](https://user-images.githubusercontent.com/1938082/79632148-0bf83d80-817b-11ea-903a-8e633447afbb.png)

Any ideas?

**Comment by chrisys** [comment]
Hey @vsaravind007 thanks for trying the project! I literally just merged a PR that adds this to the FAQ on the foldforcovid.io website, but the short of it is that you're up and running successfully and ready to go, but right now there are no jobs in the queue that will run on devices with 1GB RAM. It's still great to have your device online and ready though as when researchers submit these tasks your device will pick them up and start working straight away. 👍

**Comment by chrisys** [comment]
@vsaravind007 I'll close this one for now but also take a look at #22 which may affect you. Fix will be rolled out in the next release.
