### ISSUE TITLE
Provide landing page & interface to control devices using preflashed images

### ISSUE THREAD

**Issue by rahul-thakoor** [balenalabs/rosetta-at-home#18]
Right now, users don't have a way to remotely manage the device or even power cycle it. 
Add an interface to manage device

**Comment by ishotjr** [comment]
+1

**Comment by chrisys** [comment]
Develop this page a bit further so it also includes:

- device reboot/shutdown
- project key change
- where to find the community
- a message to leave their device on as much as possible
- wifi config
- team stats
- links to share (twitter/FB)
- a link to the dashboard (perhaps offer instructions to adopting device, if we can facilitate that)

**Comment by rahul-thakoor** [comment]
Hey @chrisys perhaps a mockup of the page will be helpful?

some of the features are being implemented [on this branch](https://github.com/balenalabs/rosetta-at-home/tree/add-simple-dashboard)

**Comment by chrisys** [comment]
![Screenshot 2020-05-01 at 19 35 30 copy](https://user-images.githubusercontent.com/521698/81057890-365d3100-8ec5-11ea-86f3-924acafc2837.png)

@iamsolankiamit he's a mockup of what we're aiming for - you'll see in the branch @rahul-thakoor linked above that we've already figured out the actions and pulled the data for the links.

Rosetta team stats should link to: https://boinc.bakerlab.org/rosetta/team_display.php?teamid=18832
View device stats should link to: https://boinc.bakerlab.org/rosetta/show_host_detail.php?hostid=
Community: https://forums.balena.io/c/fold-for-covid/
GitHub: https://github.com/balenalabs/rosetta-at-home

For the shutdown and reboot buttons these should submit the action to the supervisor (they do work as they are), and give the user some visual feedback the action has been submitted - a spinner/modal that greys out the page etc. Perhaps if they do reboot we could show something that blocks out the page for say 60 seconds, but if shutdown we don't need a timeout.

Change account key should click to bring up an input box for the user to input and save an alternative account key, but should also include a reset action to restore it to the one specified in `account_boinc.bakerlab.org_rosetta.xml`.

For the social media buttons I think we can just use the small icons (don't need buttons like the main website) and we can link them to the same actions as on foldforcovid.io
