### ISSUE TITLE
RPI 4 1Gb is not working

### ISSUE THREAD

**Issue by farv** [balenalabs/rosetta-at-home#19]
I've next logs from a RPI 4 1Gb when I push the code from master:
```
19.04.20 15:28:37 (+0200)  boinc-client  19-Apr-2020 13:28:37 [Rosetta@home] Rosetta needs 1907.35 MB RAM but only 965.88 MB is available for use.
19.04.20 15:28:37 (+0200)  boinc-client  19-Apr-2020 13:28:37 [Rosetta@home] Rosetta needs 1716.61 MB RAM but only 965.88 MB is available for use.
19.04.20 15:29:05 (+0200)  boinc-client  19-Apr-2020 13:29:05 [---] Project communication failed: attempting access to reference site
19.04.20 15:29:07 (+0200)  boinc-client  19-Apr-2020 13:29:07 [---] Internet access OK - project servers may be temporarily down.
```
Has anybody the same problem?

**Comment by rahul-thakoor** [comment]
hey @farv 
This means the work queue ran out of jobs that run on devices with lower amounts of memory. This is explained in the [FAQS here](https://foldforcovid.io/#faqs)

> This project supports devices with 1GB of RAM (or greater). However, sometimes the work queue will run out of jobs that run on devices with lower amounts of memory. This simply means your device will sit idle until jobs that have lower memory requirements are submitted by researchers. It's still great to have your device online and available for work. In this case you'll see a message that says something like "Rosetta needs 1907.35 MB RAM but only 966.82 MB is available for use.".

Hope this helps

**Comment by farv** [comment]
Of course it helps!!! Sorry for the inconveniences.
