### ISSUE TITLE
Change BALENA_MACHINE_NAME to BALENA_ARCH in ui/Dockerfile.amd64

### ISSUE THREAD

**Issue by rahul-thakoor** [balenalabs/rosetta-at-home#21]

**Comment by chrisys** [comment]
@rahul-thakoor could you the add the reasoning here, plus confirm if you mean `ARCH_NAME` or `BALENA_ARCH`?

**Comment by rahul-thakoor** [comment]
hey @chrisys , yes a typo on my part. fixed.

My reasoning is Generic x86_64 is currently using `intel-nuc` as machine name. If that were to change and the same base images were not available for some reason, the build would fail.

**Comment by rahul-thakoor** [comment]
Also, I think we can consolidate `ui/Dockerfile.template` and `ui/Dockerfile.amd64` into single `ui/Dockerfile.template`  since the only difference seems to be the arch name for downloading `gotty` which we can infer at build time using `BALENA_ARCH`
