### ISSUE TITLE
Jetson nano: Turn on fan

### ISSUE THREAD

**Issue by paroque28** [balenalabs/rosetta-at-home#26]
Please integrate: https://github.com/Pyrestone/jetson-fan-ctl
or at least turn the fan at 255 
```
sudo sh -c 'echo 255 > /sys/devices/pwm-fan/target_pwm'
```

Is there any way of getting ssh on the machine?

**Comment by chrisys** [comment]
@paroque28 could you give this PR a try: https://github.com/balenalabs/rosetta-at-home/pull/28

When you join the app from foldforcovid.io the devices are running in production mode and have no open SSH for security. If you want to tinker with the app, you could look into setting up your own balenaCloud account and flashing your device with a development mode OS, then it'll have open SSH.

Either way, let me know if the above fix helps in your situation. I've tested it on my device here so I think it's OK to roll out to production (then your device would receive the update), pending review.

**Comment by paroque28** [comment]
Great @chrisys , works well
