### ISSUE TITLE
Rosetta needs 1716.61 MB RAM but only 917.58 MB is available for use.

### ISSUE THREAD

**Issue by craigusus** [balenalabs/rosetta-at-home#32]
Hi, I'm getting the above on a Raspberry Pi 4 with 4GB of RAM. How can I utilise the maximum amount of RAM available?

**Comment by ghost** [comment]
Getting similar error on RPi 3.

**Comment by ghost** [comment]
Nevermind, if I may quote the FAQ:

> This project supports devices with 1GB of RAM (or greater). However, sometimes the work queue will run out of jobs that run on devices with lower amounts of memory. This simply means your device will sit idle until jobs that have lower memory requirements are submitted by researchers. It's still great to have your device online and available for work. In this case you'll see a message that says something like "Rosetta needs 1907.35 MB RAM but only 966.82 MB is available for use.".

**Comment by ghost** [comment]
Check to see if your device is currently running a task. If that is the case, that is probably why you are not able to run any programs.

**Comment by craigusus** [comment]
Apparently, Amazon decided to send me a 1GB version rather than the 4GB one ordered. Hence the error. Closing.
