### ISSUE TITLE
Rosetta web is reporting the use of an old URL

### ISSUE THREAD

**Issue by manuti** [balenalabs/rosetta-at-home#42]
In the **boinctui** I can see this message:

`This project is using an old URL. When convenient, remove the project, then add https://boinc.bakerlab.org/rosetta/`

If you can see the message, It appears if you go to the menu: _Projects > Rosetta@home > Update project_

I must change this by myself or not?
Thanks

I add an snapshot:

![image](https://user-images.githubusercontent.com/1991606/81057563-f5691a80-8ecc-11ea-8355-50b1d4ddc16d.png)

**Comment by chrisys** [comment]
@manuti thanks for reporting, I think this is simply requiring a change from HTTP to HTTPS. I don't think it's required that you update it and the project will continue to work, but I have just PR'd an update to the default URL to correct this.
