### ISSUE TITLE
"Deploy with Balena" button doesnt work

### ISSUE THREAD

**Issue by maximkrusina** [balenalabs/rosetta-at-home#56]
When I click on "Deploy with Balena" button on this project home page, it will open my dashboard, then I create a new app, but no release is added. I have to clone in it and deploy it from my computer via balena push

**Comment by chrisys** [comment]
@maximkrusina is this still the case? I've just tried it here and it worked great first time.

**Comment by chrisys** [comment]
Ahh actually, it's most likely linked to #54
